### ISSUE TITLE
Please, a guide or a video of more detailed installation

### ISSUE THREAD

**Issue by fdazaa** [SnowdogApps/magento2-theme-blank-sass#112]
This is a translation from google - Greetings to all, we have 4 days and we can not make our magento work with FRONTOOLS and THEME BLANK SASS, we use magento 2.1.2, we know that for you it is easy to install and use GULP for the first time We did it.

The guide a little more detailed than we found was this:
https://astrio.net/blog/magento-2-speed-local-optimization/

But also generates errors. The worst error (of several that we managed to solve) that caused us to follow the steps meticulously was> "required parameter 'theme_dir' was not passed"> this error was generated after entering the administration zone and changing LUMA by SNOWDOG THEME To solve it practically you have to reinstall magento because neither manually deleting the templates from the database and other methods was not solved. We also saw all videos of MEETUPS but none looks like starting with frontools and blank theme sass, we understand the benefits of using this but ... how to start ?:

https://www.youtube.com/watch?v=RLDjTssV3bI&t=1863s
https://www.youtube.com/watch?v=sIS7UQXq_xM&t=1292s
https://www.youtube.com/watch?v=8T573n5Kaxc

The closest we found was these guides but they are with GRUNT and it is different:
https://www.youtube.com/channel/UCURb55MT7IOMAKa56BB3slA

And also this:
https://www.youtube.com/watch?v=SzSpJqZTSi8
But do not use FRONTOOLS.

We are not advanced users and we know that it could be obvious and easy to install but we did not do it, we did not go any further than asking for help. A simple little video or a 

> step by step guide from scratch for frontools + theme blank theme + LiveReload

would help everyone who wants to follow this project and learn more.

**Thank you! :)**

**Comment by Igloczek** [comment]
Thanks for letting us know that this type of guide is needed.
I'll try to create a short video with detailed description, hope that will help you understand how to handle installation process and further maintenance.

**Comment by Freddie-Daza** [comment]
Thanks @Igloczek  for responding, really if a help **guide for beginners** is needed. We will be very grateful. We look forward to the video to understand that we are doing badly in our installation and thus to be able to follow carefully the snowdog project.

**Comment by gil--** [comment]
I can make a simple Youtube video on setting it up and using it. Give me like a week.

**Comment by fdazaa** [comment]
gil-- that would be great. What is your youtube channel to subscribe to. I'm still attentive to continue with the project.

**Comment by michaeljonathanblack** [comment]
Any further clarification, here? I'm about to set this up and well... this issue makes me wary

**Comment by michaeljonathanblack** [comment]
Nevermind, everything worked! 

If I knew how to make a video, I'd do a screencast. In lieu of that, here's a markdown readme I made while walking through all of the steps.

Note: The following steps are based on using the Docker instance for Magento2 Community Edition.

## Setup Sass
To setup Sass for this project, please walk through the following steps.

### Install [Blank Sass Theme][4]

#### Inside the interactive shell

```
cd magento2
composer require snowdog/theme-blank-sass
cd bin
magento setup:upgrade
magento setup:di:compile
```

### Install [Frontools][5]

This is the development tool used to handle Sass compilation and browser live reloading, just follow the commands below. 

#### Inside the interactive shell

Install frontools

```
cd magento2
composer require snowdog/frontools
```

#### Locally

Install nvm

```
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
nvm install --lts
nvm use --lts
```

Install gulp-cli

```
npm install -g gulp-cli
```

Install frontools dependencies

```
cd <docker_installation>
cd shared/webroot/vendor/snowdog/frontools
npm install
```

Generate the following configuration files using the samples located inside `shared/webroot/vendor/snowdog/frontools/config`
- `/dev/tools/frontools/config/browser-sync.json`
- `/dev/tools/frontools/config/sass-lint.yml`
- `/dev/tools/frontools/config/stylelint.yml`
- `/dev/tools/frontools/config/themes.json`

### Compile Sass

#### Locally

```
cd <docker_installation>
cd shared/webroot/vendor/snowdog/frontools
gulp dev
```


[1]: https://magento.com/tech-resources/downloads/magento/configure/form_key/LUrsF2E0m0ZRTiu1/
[2]: https://www.docker.com/products/docker
[3]: http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/css-topics/css_debug.html#grunt_prereq
[4]: https://github.com/SnowdogApps/magento2-theme-blank-sass
[5]: https://github.com/SnowdogApps/magento2-frontools

**Comment by Igloczek** [comment]
For now, we are not planning any additional resources.
