### ISSUE TITLE
magento/framework 100.1.*

### ISSUE THREAD

**Issue by matthew-scioneaux** [SnowdogApps/magento2-theme-blank-sass#113]
I have been using an older version of Frontools for over a year. It has been immensely useful to me, thanks for that. I just upgraded so I wanted to try your SASS theme. 

I have no problems with my Magento 2.2 install or frontools, but cannot do a composer install of the SASS theme for versions higher than 0.6.

Problem 1
    - Installation request for snowdog/theme-blank-sass ^0.9.2 -> satisfiable by snowdog/theme-blank-sass[0.9.2].
    - snowdog/theme-blank-sass 0.9.2 requires magento/framework 100.1.* -> no matching package found.

Is there a work-around for this? 

Thank you,
Matthew

**Comment by Igloczek** [comment]
We are supporting only offical releases, but 2.2 isn't released yet. If you want to use this theme on developent version of M2, you need yo fork this repo and make necessary modifications. In this case you probably need to change of required magento/framework version to 100.2.*
