### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by kitecom** [SnowdogApps/magento2-theme-blank-sass#114]
Hi - just trying to install the Blank SASS theme to a Magento2 install... 
Running "composer require snowdog/theme-blank-sass" and seeing the following error:
"Problem 1
    - Installation request for snowdog/theme-blank-sass ^0.9.2 -> satisfiable by snowdog/theme-blank-sass[0.9.2].
    - snowdog/theme-blank-sass 0.9.2 requires magento/framework 100.1.* -> no matching package found."

Magento ver. 2.2.0-dev
Composer v 1.2.2
All on https://github.com/paliarush/magento2-vagrant-for-developers

**Comment by Igloczek** [comment]
Same as #113
