### ISSUE TITLE
Port of Less MagentoUI Docs

### ISSUE THREAD

**Issue by gil--** [SnowdogApps/magento2-theme-blank-sass#115]
Is there any existing effort to port the [MagentoUI docs](http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-topics/theme-ui-lib.html#docs) from Less to Sass?

- [Demo of Docs](http://magento2-demo.nexcess.net/pub/static/frontend/Magento/blank/en_US/css/docs/buttons.html)

- [Doc Source in Less example](https://github.com/magento/magento2/blob/develop/lib/web/css/docs/source/_buttons.less)

**Comment by Igloczek** [comment]
Nope. I have in plan adding new docs during Magento UI rewrite (to add have template in docs, not only styles), but there is no date or deadline here.

TBO we are currently looking for different approach of working with M2.
