### ISSUE TITLE
What about using "Element Queries" in this theme?

### ISSUE THREAD

**Issue by hpvd** [SnowdogApps/magento2-theme-blank-sass#119]
just have a look at "Element Queries"

for me (no magento dev) it make absolutely sense to use element queries - especially in ecommerce shops with it's many many recurring elements:

basics:
http://hugogiraudel.com/2014/04/22/why-element-queries-matter/

after that
https://marcj.github.io/css-element-queries/

respectively: https://github.com/marcj/css-element-queries

**Comment by Igloczek** [comment]
Yet another fancy framework.. 
I'm not going to rewrite this theme once again. Invest your time, fork this theme, implement proposed solution and share your work with rest of the community if you really think it's worth it 😉
