### ISSUE TITLE
Use !default flag for all variables

### ISSUE THREAD

**Issue by thijsvandberg** [SnowdogApps/magento2-theme-blank-sass#121]
It would be nice to have all variables defined with a !default flag.
```
$primary__color: $color-gray20 !default;
```
That way you don't have to copy entire files in your child-theme, but you can just change a few variables before importing the default theme-blank-sass `_variables.scss` file.

**Comment by Igloczek** [comment]
You can always create another file with variables overwrites / own variables and import them **after** `_variables.scss`.
I'm a big fan of basing everything on execution order, so didn't see a reason for this type of change.

**Comment by thijsvandberg** [comment]
I see two big advantages of defining those variables with a !default flag:

1. When you want to change the color of the header icons, you can change the `$header-icons-color` variable in `Magento_Theme/styles/_module.scss`, but you have to copy the entire `_module.scss` file to do so. If you define `$header-icons-color before` or after `_variables.scss` it gets redefined when `_module.scss` is executed. 
2. When you want to change the primary color, you can define `$primary__color` after Snowdog's `_variable.scss`, but at that point a lot of other variables are defined based on the previous primary color. When you can define the primary color before `_variables.scss` and `magento-ui`, you don't have to redefine 20+ variables because one variable is changed.

I'd like to keep my child-theme as small and organised as possible. I already changed all variables for my current project, if you agree with my points I could create a pull request.

**Comment by Igloczek** [comment]
You are right, I forgot about variables depending on other variables. So I'm looking forward to your PR :wink:

**Comment by Igloczek** [comment]
Merged, will be released with 0.10.0.
