### ISSUE TITLE
Add new module partials without having to overwrite entire module

### ISSUE THREAD

**Issue by gil--** [SnowdogApps/magento2-theme-blank-sass#123]
I'm wondering if we can consider moving the module-specific styling to partials to avoid having to overwrite the entire file in order to import a new module.

**Example**.

I want to add a new module to *Magento_Catalog* but I need overwrite the entire [module](https://github.com/SnowdogApps/magento2-theme-blank-sass/blob/master/Magento_Catalog/styles/_module.scss) file. Instead, it would be nice if we could separate all the [module styling](https://github.com/SnowdogApps/magento2-theme-blank-sass/blob/master/Magento_Catalog/styles/_module.scss#L30) into a partial like `_module-base.scss` or equivalent.

At the moment, in my child theme, I would need to overwrite *Magento_Catalog/../_module.scss* just to import another module.

Is this too large of an architectural change to consider?

**Comment by Igloczek** [comment]
In ideal world `_module.scss` files contains only imports to module partials, but M decided to put here a loooooot of code, which make everything messy and hard to use.

So if you want to make world a better place, move this code to separate partials (following some logic ofc) and create a PR, b/c I'd love to click "Accept pull request" 😉

**Comment by gil--** [comment]
Closing this Issue. Discussion can continue on PR https://github.com/SnowdogApps/magento2-theme-blank-sass/pull/124
