### ISSUE TITLE
New release of develop branch changes?

### ISSUE THREAD

**Issue by gil--** [SnowdogApps/magento2-theme-blank-sass#129]
Any plans for a [release](https://github.com/SnowdogApps/magento2-theme-blank-sass/releases) soon with the [develop changes](https://github.com/SnowdogApps/magento2-theme-blank-sass/compare/master...develop?expand=1)?

I'm wondering how you decide when to issue a new release.

**Comment by Igloczek** [comment]
I'm just doing this in free time or/and when I/someone need something.
0.10.0 released, enjoy 😉

**Comment by gil--** [comment]
@Igloczek Many thanks! Very much appreciated. 👊 😃
