### ISSUE TITLE
Fotorama alignment issues

### ISSUE THREAD

**Issue by zamson** [SnowdogApps/magento2-theme-blank-sass#130]
I'm having trouble with the fotorama gallery and alignment. In our store images differ in proportions per category and Fotorama does not respect this. The alignment is off. This is not the case with the default luma theme.  It seems like the problem is related to the div **fotorama__stage** which gets a height by the js.

Is there any setting to make Fotorama adjust to the image?

<img width="601" alt="screen shot 2017-02-14 at 11 08 56" src="https://cloud.githubusercontent.com/assets/11811478/22924832/e55bca18-f2a6-11e6-9449-3b010246a5d0.png">

**Comment by Igloczek** [comment]
@niemaco could you take a look at this?

**Comment by zamson** [comment]
Any updates? Is it possible to remove your implementation or will that just render Fotoroama without any CSS at all?

Edit: Can confirm that the gallery goes by settings in view.xml and then does aspect calculation which means only one image size is allowed.

There is a bug when using vertical thumbnails where fotorama does not respect the width of the thumbnails and still adds same width to image thus moving the main image down and creating white space.

**Comment by Igloczek** [comment]
Something like "our implementation of Frotorama" is a bit of overstatement. We just take messy styles from M, divide them to smaller partials and include directly into the theme.

Any template, JS or XML related things wasn't modified, so if you are facing some issues in that matter, unfortunately, it's not a right place to ask questions this type of questions.

From my perspective, you just don't like a default behavior of centering images and it's not a bug. Are you sure your image is big enough to fill up space without over scalding?

**Comment by RiaParshina** [comment]
If it's still relevant for someone, there's a post about it here: https://thiscodemightwork.wordpress.com/2017/07/20/how-to-position-fotorama-in-magento-2-and-avoid-white-space-around-the-image/
Worked for me with the same issue!

**Comment by Januszpl** [comment]
@RiaParshina post is not accessible.

**Comment by RiaParshina** [comment]
@Januszpl I've updated the link

**Comment by Januszpl** [comment]
@zamson have you resolved you issue? Have you also checked this on magento blank theme? (less version?) and clear steps to reproduce it on clean magento with sass-blank would be appreciated.

@RiaParshina thanks for the link.

**Comment by Igloczek** [comment]
Closing due to lack of feedback about reproducing it on the LESS based "Blank" theme.

**Comment by sagarppanchal** [comment]
This solution worked for me, hope it will help others as well.

Place this code just after your code in gallery.phtml file
```
<script type="text/javascript">
    require(
    [
        'jquery',
        'jquery/ui'
    ],
    function(
        $
    ) {
        $(window).load(function(){
            console.log("readyyy");
            $(".fotorama__stage").height($(".fotorama__img").height());

            $( window ).resize(function() {
                console.log("resize");
              $(".fotorama__stage").height($(".fotorama__img").height());
            });
        })
    });
</script>
```
