### ISSUE TITLE
Unused variables in magento-ui\_forms.scss

### ISSUE THREAD

**Issue by RetroModernDev** [SnowdogApps/magento2-theme-blank-sass#133]
Hi,

at the beginning of the file `theme-blank-sass\styles\vendor\magento-ui\_forms.scss` they are declared variables ex. `$form-element-input__background`  but it is not used in `@mixin lib-form-element-input`. 

For example in mixin we have: 

`$_background                : $color-white;`

Should be: 

`$_background                : $form-element-input__background`

At this moment it is not possible to overwrite mixin variables without overwrite mixin.

**Comment by Igloczek** [comment]
Good catch. Could you create a PR with fix?
I'm extremely busy and it will stay intact for at least a few weeks.

**Comment by RetroModernDev** [comment]
No problem, i will fix this issue. :)
