### ISSUE TITLE
Magento UI LESS -> SASS conversion issues

### ISSUE THREAD

**Issue by Skepton** [SnowdogApps/magento2-theme-blank-sass#136]
In the Magento UI library included with this theme (/styles/vendor/magento-ui/) there are several mixins, and combinations of mixins, that are for all intens and purposes 'broken' in its current implementation. My guess is that most of there have been converted from LESS to SASS entirely though automatic means.

The problem with this is that certain LESS-patterns are not transferabel to SCSS. As an example have a look at this section of code in the _grids.scss file:

```
@mixin lib-column() {
    float: left;
    @include lib-column-gutter();
}

@mixin lib-column($span) {
    @if $span != true {
        float: left;
    }
}

@mixin lib-column(
    $span,
    $total-columns: $total-columns,
    $end-column   : inherit
) {
    @if isnumber($span) {
        @if isnumber($total-columns) {
            @if isnumber($end-column) {
                $showgutter: inherit;
                @include lib-column($showgutter);
...
```

In LESS these multiple mixins would all be used depending on the number of arguments entered when using them, since LESS supports overloading of mixins. In SCSS this is a very redundant way of writing the last "version" of that mixin, leaving the mixins set before the last instance overwritten. I'm also unsure of if that last instance would give the proper results if used.

There are more examples of this throughout the Magento UI library. It seems like these functions are not in use at the moment, since they would probably result in a compile error when used as "intended". But the point of having a complete port of the Magento UI Library is somewhat lost if it is not working completely.

Does anyone have any thoughts on a way to move forward with this? I also find it a bit wierd that there are functions / mixins in the Magento UI library that is not in use by the theme itself, and such a major thing as mixins for the handling of columns & layout. But this is consistent with the Magento LESS theme too though.

**Comment by Igloczek** [comment]
Magento UI is shared between admin and front-end area, that's why we have unused parts.

I'll be happy to merge any PR with improvements in this area.
