### ISSUE TITLE
Child theme

### ISSUE THREAD

**Issue by HyperC** [SnowdogApps/magento2-theme-blank-sass#137]
I've created a child theme of Snowdog, but having trouble to create my own styles. Adding a new styles.scss to the new theme folder clears the Snowdog styles, so I thought maybe I have to add an import like so:

@import '../../../../../../vendor/snowdog/theme-blank-sass/styles/styles.scss'; // snowdog base styles

But that doesn't seem to be the way to go. What is?

**Comment by talalus** [comment]
you need to copy styles.scss from parent theme to the child theme.

**Comment by HyperC** [comment]
Ah, I see. But then you can't really perform updates in any easy way. But alright, I'll do that.

**Comment by HyperC** [comment]
But then I have to copy everything, all its dependencies (imports) as well..

**Comment by talalus** [comment]
No you don't have to copy everything only style.scss and any scss file you want to override it, frontool will handle the inheritance for the rest of files. and for the later update it'll not be that hard to handle the diff on styles.scss since you are adding new import to it

**Comment by HyperC** [comment]
Okay cool :)
