### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by acidjunk** [SnowdogApps/magento2-theme-blank-sass#140]
Seems a really nice project. Just a quick question:
Would it be possible to support older browsers, like MSIE8-10 by using your blank theme?

**Comment by Igloczek** [comment]
Nope, b/c platform doesn't support it too.
>Internet Explorer 11 or later, Microsoft Edge, latest–1

http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements_browsers.html

**Comment by acidjunk** [comment]
I know Magento doesn't support it but is seems mostly related to IE support max 4096 CSS selectors. https://magento.stackexchange.com/questions/121454/media-common-less-not-displaying-in-ie-9/121794

Was just wondering, as your theme seems to NOT inherit from Luma. Guess have to check it myself :)

Thanks for the quick reply.

**Comment by Igloczek** [comment]
You might try to use http://blesscss.com/
But at all, I'm not interested in wasting time to support unsupported and outdated browsers, which are just pain in the ass, nothing more 😉 

BTW. Luma is the child theme of Blank.
PS. I believe it's not only CSS issue, there is a lot of JS, milion ways to something go wrong.
