### ISSUE TITLE
magento-ui/_navigation should use variables

### ISSUE THREAD

**Issue by amenk** [SnowdogApps/magento2-theme-blank-sass#143]
Example:

    //
    //  Navigation
    //  ---------------------------------------------
    
    $_nav-level0-item-background-color : inherit !default;
    
    @mixin lib-main-navigation(
        $_nav-level0-item-background-color       : $_nav-level0-item-background-color,

**Comment by amenk** [comment]
see https://github.com/iMi-digital/magento2-theme-blank-sass/commit/d6a3a9d34982144835f04f8e38662af53e3ea957

**Comment by Igloczek** [comment]
Feel free to submit a pull request 😉
