### ISSUE TITLE
Preparing for Magento 2.2 - magento/framework 100.2.*

### ISSUE THREAD

**Issue by fransy-halo** [SnowdogApps/magento2-theme-blank-sass#150]
I am testing this theme on  Magento 2.2 RC. However, when running composer require snowdog/theme-blank-sass I see this problem:
 
snowdog/theme-blank-sass 0.10.1 requires magento/framework 100.1.* -> no matching package found.
 
As of today, Magento 2.2 RC comes with magento/framework 100.2.0-dev

**Comment by kweij** [comment]
Will Snowdog provide support for future release of Magento concerning this theme?

**Comment by Igloczek** [comment]
Yup, but only for stable releases. 

I'm not going to make this package compatible with alpha / beta / RC / whatever releases - if you want to test it - fork  -> customize -> use
