### ISSUE TITLE
Support for Magento 2.2

### ISSUE THREAD

**Issue by dennisfalkner1** [SnowdogApps/magento2-theme-blank-sass#159]
When trying to upgrade to Magento 2.2 via composer, im getting this error

`- The requested package snowdog/theme-blank-sass ^0.10.2 exists as snowdog/theme-blank-sass[0.10.0, 0.10.1, 0.2.0, 0.2.1, 0.2.2, 0.3.0, 0.4.0, 0.5.0, 0.5.1, 0.5.2, 0.6.0, 0.7.0, 0.7.1, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.9.1, 0.9.2, dev-develop, dev-feature/32702, dev-master] but these are rejected by your constraint.`

Is there a fix for this, or will the theme be updated for magento 2.2?

**Comment by Igloczek** [comment]
Version with 2.2 support will be released soon

**Comment by Igloczek** [comment]
2.2 support requires more work than I expected, so for now, I released v0.11.0 as pack of updates for 2.1

Next release will bring more changes to come back closer to core code and simplify maintenance, b/c project target changed over time.
