### ISSUE TITLE
Unable to compile with sass after moving from 0.11.0 to 1.0.1

### ISSUE THREAD

**Issue by rob3000** [SnowdogApps/magento2-theme-blank-sass#168]
When trying to include and compile the sass getting the following errors `(Line 313 of vendor/snowdog/theme-blank-sass/styles/vendor/magento-ui/_pages.scss: Invalid CSS after "...r-item-display ": expected "{", was "= inline-block {")
` this is due to the following change https://github.com/SnowdogApps/magento2-theme-blank-sass/blob/0.11.0/styles/vendor/magento-ui/_loaders.scss#L49

PR created https://github.com/SnowdogApps/magento2-theme-blank-sass/pull/167

**Comment by Igloczek** [comment]
Fixed in 384a7f4fce9a9727ffb340fe5259888966e18e3a will be relased with 1.1.0
