### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by iamface** [SnowdogApps/magento2-theme-blank-sass#171]
Hello,

I'm trying to run `composer require snowdog/theme-blank-sass` and getting an `Invalid credentials for 'https://repo.magento.com/packages.json', aborting.`

I am able to log into the Magento marketplace just fine. Is this a different account that I'm missing?

Thanks

**Comment by Igloczek** [comment]
Sorry, but it's not an issue related to this module.

Follow the Magento DevDocs to setup credentials correctly: http://devdocs.magento.com/guides/v2.2/install-gde/prereq/connect-auth.html

**Comment by iamface** [comment]
Perfect, thank you! I figured it was something I was missing. Cheers
