### ISSUE TITLE
Mobile Menu Account Links not copied over

### ISSUE THREAD

**Issue by drdreamm** [SnowdogApps/magento2-theme-blank-sass#182]
Hi Snowdog 

There seems to be an issue with the inclusion of the theme.js file which copies over the account menu items to the mobile menu account tab.  The Account tab is empty.

**Comment by Igloczek** [comment]
Indeed something is wrong, b/c we have more JS files than the LESS version of the Blank theme. I'll check it out.

**Comment by drdreamm** [comment]
I found a solution : I copied files (requirejs-config.js and the missing JS files ) from magento2ce/vendor/magento/theme-frontend-blank/Magento_Theme to the theme that I am using to extend blank /app/design/frontend/COMPANY/blank/Magento_Theme   and it worked - so it's wasn;t including these 

![screen shot 2018-01-10 at 17 42 16](https://user-images.githubusercontent.com/1238155/34784186-e7d48146-f62d-11e7-8a05-4c70051ae1f1.png)

**Comment by Igloczek** [comment]
Please update to 1.0.4, I updated all JS according to the changes in Magento core.

**Comment by drdreamm** [comment]
cool thx
