### ISSUE TITLE
Theme breaks if $font-size-unit-convert: false !default; is set

### ISSUE THREAD

**Issue by amenk** [SnowdogApps/magento2-theme-blank-sass#191]
We set font-size-unit-convert to false, then we are 
getting this invalid CSS output where the font size is missing the unit

	.column.main .abs-discount-block > .title strong, .column.main .cart-summary .block > .title strong, .cart-summary .column.main .block > .title strong, .column.main .paypal-review-discount .block > .title strong, .paypal-review-discount .column.main .block > .title strong {
	    font-size: 18;
	    font-weight: 300;
	}

Should we change 

	@function lib-font-size-value($_value) {
	    @if $font-size-unit-convert {
		@if $_value != false and $_value != '' {
		    $_value: strip-unit($_value) / $font-size-unit-ratio;
		    @if $_value > 0 {
		        $_value: $_value * 1#{$font-size-unit};
		    }
		    @return $_value;
		}
	    }
	    @else {
		@return $_value;
	    }
	}

to per default append the default unit?
Or change occurrences like  lib-font-size(18) (see https://github.com/SnowdogApps/magento2-theme-blank-sass/blob/master/styles/blocks/_extends.scss#L151) to actually contain a unit ?

**Comment by Igloczek** [comment]
It looks like a bug inherited from the LESS based theme, so we should fix it in the core first and then add same changes here.

If I'll have to choose the solution, I'd go with adding a `px` to the `lib-font-size` params, since these values should always have a unit.

**Comment by Igloczek** [comment]
[We are closing this project.](https://github.com/SnowdogApps/magento2-theme-blank-sass/commit/77253d24ab00c05b2b91693fb25aeac4bebfa1de)
