### ISSUE TITLE
wrong position for message icon

### ISSUE THREAD

**Issue by talalus** [SnowdogApps/magento2-theme-blank-sass#194]
![image](https://user-images.githubusercontent.com/3689740/45265648-849b0200-b44e-11e8-9a60-7e2c5e96e640.png)
it's already set right in https://github.com/magento/magento2/blob/2.0/lib/web/css/source/lib/_messages.less#L238 so no need for a pull request to magento UI

**Comment by Igloczek** [comment]
You don't need to open issue for PR and will be nice to link them ;)
