### ISSUE TITLE
Incorect number divisions in sass

### ISSUE THREAD

**Issue by lumnn** [SnowdogApps/magento2-theme-blank-sass#197]
Some Scss files contains a math calculations that are not calculated in compiled CSS file.

Compiled CSS:
![image](https://user-images.githubusercontent.com/2505114/46348833-2970bf80-c648-11e8-88f6-01031b85908b.png)

Example line from repository:
https://github.com/SnowdogApps/magento2-theme-blank-sass/blob/1.1.3/Magento_Catalog/styles/_widgets.scss#L74

Sass documentation on divisions: http://sass-lang.com/documentation/file.SASS_REFERENCE.html#division-and-slash

**Comment by Igloczek** [comment]
Thanks for reporting, feel free to submit PR that will fix it.
Would be also great to check the stylelint settings, because it should detect not valid CSS.

**Comment by lumnn** [comment]
Submitted PR #198

**Comment by Igloczek** [comment]
Relased as v1.2.0
