### ISSUE TITLE
gulp-notify: [Error running Gulp] Undefined variable: "$loader-overlay--z-index"

### ISSUE THREAD

**Issue by keivan85** [SnowdogApps/magento2-theme-blank-sass#199]
I am trying to build a theme using magento2-theme-blank-sass as parent. I installed the snowdog front tool, theme-blank-sass & my theme via composer. I ran `npm install` and then `gulp setup` & edited the themes.json file. I added my theme to `/dev/tools/frontools/config/themes.json` file.

The issue is whenever I run `gulp styles` under `My_Project/vendor/snowdog/frontools`, it throws a gulp error for an `Undefined variable: "$loader-overlay--z-index"`.
This variable is used in `magento2-theme-blank-sass` in `_variables.scss` & `_loader.scss`. The variable is coming from `My_project/var/view_processed`.
`/var/view_preprocessed/frontools/frontend/My_project/en_US/styles/vendor/magento-ui/_loaders.scss`
If I try to to run `gulp styles` with just basic magento2-theme-blank-sass, it will compile. But if I add my theme the error shows up in compile. It seems that parenting inheritance is not working correctly. 
I tried to delete cache and view_processed and then regenerate files, but the issue still exist.

I am using Magento 2.1.15, snowdog front tool 1.3.0, magento2-theme-blank-sass 0.11.1.

**Comment by Igloczek** [comment]
Show how your `config/themes.json` looks like, I think you just don't have the `parent` set or this variable really don't exist.

BTW. Do not post the same issue on both forum and github, it's pointless 😉

**Comment by keivan85** [comment]
Sorry, github was down today and after posting the issue, it didn't show up. I decided to repost/rewrite it on community.
this is my themes.json file
```
{
    "blank": {
        "src": "vendor/snowdog/theme-blank-sass",
        "dest": "pub/static/frontend/Snowdog/blank",
        "locale": [
            "en_US",
            "fi_FI",
            "sv_SE"
        ],
        "ignore": [
            ".test"
        ]
    },
    "mytheme": {
        "src": "vendor/myproject/mytheme",
        "dest": "pub/static/frontend/myproject",
        "locale": [
            "en_US",
            "fi_FI",
            "sv_SE"
        ],
        "parent": "blank"
    }
}
```
