### ISSUE TITLE
Checkout Step Title variables 

### ISSUE THREAD

**Issue by jeroenalewijns** [SnowdogApps/magento2-theme-blank-sass#202]
Today I wanted to change the step titles used in the checkout. I couldn't reset the border bottom of the step title below what I found out:

In `magento2-theme-blank-sass/styles/blocks/_extends.scss` on ln 1142 the class `.abs-checkout-title` is set which is used for the checkout titles. In that file on line 1143 the variable `$checkout-step-title__border` is used.
This variable is set in file `magento2-theme-blank-sass/Magento_Checkout/styles/module/checkout/_checkout.scss` on ln 8.

After that I had changed this variable the changes where not visible.

Did some research and found out that in file `magento2-theme-blank-sass/styles/_variables.scss` on ln 47 there is a variable named `$checkout-step-title__border`. This one is used!

How is that and why are there 2 different locations for `$checkout-step-title__border` which isn't used if you ask me.

I'm a bit confused. Maybe I'm doing something wrong but if you ask me I had removed the `$checkout-step-title__border` from the `_checkout.scss` ln 8.

The above also applies for `$checkout-step-title__padding`.

**Comment by Igloczek** [comment]
Well, it's not code that we wrote, it's just port of LESS theme from Magento 2 core, so according to [contribution rules](https://github.com/SnowdogApps/magento2-theme-blank-sass#bug-reports-and-contribution-rules) you need to fix this in the core, then, when your proposal will be merged to the core, we will update this theme.
