### ISSUE TITLE
Support for Magento 2.3

### ISSUE THREAD

**Issue by robertkent** [SnowdogApps/magento2-theme-blank-sass#203]
Just wondering if you're working on the 2.3 release for the blank theme? Currently it halts the composer upgrade process as the magento/framework packages defined are out of date (due to PHP version if you're using 7.2).

**Comment by dverkade** [comment]
Hi,

We have been testing with Magento 2.3. The theme works perfectly (by placing it in the app/code folder). The only issue is the composer constraint which should be changed as is mentioned in this PR: SnowdogApps/magento2-theme-blank-sass#201

**Comment by Igloczek** [comment]
Relased as v1.2.0

**Comment by robertkent** [comment]
perfect thank you
