### ISSUE TITLE
Slack Support

### ISSUE THREAD

**Issue by sivasdescalzo** [SnowdogApps/magento2-theme-blank-sass#212]
I am trying to connect my Slack with https://github.com/SnowdogApps/magento2-theme-blank-sass repo in order to get notifications everytime there is a release, but it seems GitHub Slack APP needs some permissions to the repo to do that.

Cloud you please install GitHub Slack APP in your repo in order to be able to connect Slack with your repo?
Many thx!

**Comment by Igloczek** [comment]
I can't set access globally to any app, especially while it gives any kind of write privileges, but also this app doesn't support notifications about releases. 

Set proper watch settings instead: 
![image](https://user-images.githubusercontent.com/5119280/61322028-1a40b400-a80d-11e9-9f70-24156dfe7193.png)
