### ISSUE TITLE
Check possible lack of styles from reCaptcha module

### ISSUE THREAD

**Issue by Januszpl** [SnowdogApps/magento2-theme-blank-sass#228]
Issue related to: 
https://github.com/magento/magespecialist_ReCaptcha/issues/48

In project desribed in above issue and with one of my project that is based on older version of sass blank there is issue with visible checkbox and problem wih sending contact form on Magento 2.3.3

Check if new version has all required styles.

**Comment by Igloczek** [comment]
[We are closing this project.](https://github.com/SnowdogApps/magento2-theme-blank-sass/commit/77253d24ab00c05b2b91693fb25aeac4bebfa1de)
