### ISSUE TITLE
@mixin lib-font-face missing font-display

### ISSUE THREAD

**Issue by readio** [SnowdogApps/magento2-theme-blank-sass#232]
Pretty much as the title says. The 'lib-font-face' mixin in 'styles/vendor/magento-iu/_typography.scss' is missing 'font-display: swap'.

Not a major issue, but it gets flagged up on Google PageSpeed Insights

**Comment by Igloczek** [comment]
Is that a part of the Blank theme in Magento core? If not, please read [readme](https://github.com/SnowdogApps/magento2-theme-blank-sass/blob/master/README.md#bug-reports-and-contribution-rules).

**Comment by Stevie-Ray** [comment]
it is: https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/css-topics/using-fonts.html

https://github.com/magento/magento2/blob/9544fb243d5848a497d4ea7b88e08609376ac39e/lib/web/css/source/lib/_typography.less

i've added it in #233  for now you can override the mixin to fix the issue.

**Comment by Stevie-Ray** [comment]
@Igloczek can you please update the scss to reflect the changes in Magento (2.3+) source code

**Comment by Igloczek** [comment]
@Stevie-Ray we are not using this theme in our company anymore, so there is no interest in doing such changes, but if you need them, please prepare a pull request, we will merge it and release it.

**Comment by Igloczek** [comment]
[We are closing this project.](https://github.com/SnowdogApps/magento2-theme-blank-sass/commit/77253d24ab00c05b2b91693fb25aeac4bebfa1de)
