### ISSUE TITLE
Magento 2.4 compatibility

### ISSUE THREAD

**Issue by dverkade** [SnowdogApps/magento2-theme-blank-sass#241]
This theme is not installable with Magento 2.4.0 due to the version restrictions in the composer.json file. It requires magento/framework ^101.0.0 or ^102.0.0 while Magento 2.4.0 has version 103.0.0 of the magento/framework package.

**Comment by Igloczek** [comment]
Thanks for the report Danny. Did you try to change those ranges locally and test if the theme is still okay on 2.4.0?

**Comment by dverkade** [comment]
No, this happened when I installed a clean Magento 2.4.0 instance and wanted to have our frontend on top of it (which uses the blank sass theme) to be sure that everything was working with 2.4.0. At this point the module will not install with composer due to the version constraints.

**Comment by Igloczek** [comment]
You can now try a version with correct dependencies range using
```
composer require snowdog/theme-blank-sass:dev-2.4.0-support
```
Any feedback about some compatibility issues is welcome.

**Comment by dverkade** [comment]
@Igloczek I can confirm this works with Magento 2.4.0. Can this be merged into the master and released as a new version?

**Comment by Igloczek** [comment]
@Alanaktion @drewid82 I see that you 👍 , did you tried it and can also confirm that it works?
I don't have time to check this out on my own, but if few people will confirm it, I'll make the release.

**Comment by andrewmarksmith** [comment]
@Igloczek yes it works and I'm using it as we speak!

**Comment by erighetto** [comment]
@Igloczek yes, it works also for me and I'm using in production environment

**Comment by Igloczek** [comment]
Thanks guys for a quick reply!

The v1.5.0 with support for 2.4 is released.
I'll keep the temp branch for few more weeks to give you time to update.
