### ISSUE TITLE
Tooltip label not rendering properly

### ISSUE THREAD

**Issue by Shashank-Bhatt1** [SnowdogApps/magento2-theme-blank-sass#248]
On file theme-frontend-blank/Magento_Checkout/web/css/source/module/checkout/_tooltip.less Line no 58

```
.label {
    .lib-visually-hidden();
}
```
But at `theme-blank-sass/Magento_Checkout/styles/module/checkout/_tooltip.scss` no equivalent scss definition found to hide the label.

![screenshot-local my-bmi co uk-2021 05 03-15_40_12](https://user-images.githubusercontent.com/24728257/116864711-ec1ca600-ac25-11eb-9d62-b3104f925aed.png)

**Comment by Igloczek** [comment]
[We are closing this project.](https://github.com/SnowdogApps/magento2-theme-blank-sass/commit/77253d24ab00c05b2b91693fb25aeac4bebfa1de)
