### ISSUE TITLE
Magento 2.4.3 - Page Builder

### ISSUE THREAD

**Issue by Stevie-Ray** [SnowdogApps/magento2-theme-blank-sass#254]
Magento / Adobe Open Source 2.4.3 now supports page builder by default, it uses a `_module.less` to import all page builder content-types which uses .less variables like:
```
        &.pagebuilder-button-primary {
            .lib-link-as-button();
            .lib-button-primary(@_button-margin: 0 10px 10px 0);
            .lib-button-l();
            .lib-css(border-radius, @button__border-radius);
            box-shadow: none;
        }
```
It would be very nice to have this as a frontools / blank-sass feature or a new package to use next to the these awesome tools!

**Comment by digiltd** [comment]
You mean like...

https://github.com/SnowdogApps/magento2-theme-blank-sass/tree/master/Magento_PageBuilder/styles

https://github.com/SnowdogApps/magento2-theme-blank-sass/blob/master/Magento_PageBuilder/styles/modules/content-type/button-item/_default.scss#L32

?

:)
