### ISSUE TITLE
Same breakpoints used for min-width and max-width mqs

### ISSUE THREAD

**Issue by rocketweb-fed** [SnowdogApps/magento2-theme-blank-sass#36]
Same variables are used in both min-screen and max-screen mixins ($screen__xs, $screen__s etc.). This might cause issues with overlapping rules when both mqs are used on the same element. Introduction of additional max-screen variables would be a good idea.

**Comment by Igloczek** [comment]
What a mess 😞  I think we should just change global MQ pattern or just fix it using `+ 1px` / `- 1px`, instead of creating another confusing variables.

**Comment by Januszpl** [comment]
Closing this issue as merged changes fixed it
