### ISSUE TITLE
Layered navigation - accordion/mobile nav not working

### ISSUE THREAD

**Issue by rocketweb-fed** [SnowdogApps/magento2-theme-blank-sass#41]
Looks like layered navigation was imported from Luma, but only partially, without the behavioral layer. Since JS is missing for those elements accordion and mobile navigation don't work. 

Suggested solution is to get rid of Luma based styles and revert it back to the Blank theme. Either that or importing navigation related JS is necessary.

**Comment by Igloczek** [comment]
First of all, thanks so much for your contributions!

We have some problems with few elements, b/c somehow we translated parts of Luma theme... But I have no idea why 😉 

BTW. Let's catch me on twitter (@igloczek) or send me an email - I have some really good news to share 😄

**Comment by Igloczek** [comment]
Default blank styling restored.
