### ISSUE TITLE
make sass version not scss?

### ISSUE THREAD

**Issue by theskillwithin** [SnowdogApps/magento2-theme-blank-sass#42]
can we make a sass version, maybe i can help.

also I noticed when u save a __.scss file the compiler is not ran.   should be so that it watches for save on __.scss triggering compile on .sass

**Comment by Igloczek** [comment]
Watching issue fixed in 0.8.2.

If you need strict "sass" syntax, duplicate `helpers/scss.js` and save as `sass.js` - everything should works fine.

I'm not going to add strict SASS support to this tools, b/c most of devs use scss and it's super easy to customize them.
