### ISSUE TITLE
Child theme workflow

### ISSUE THREAD

**Issue by slackerzz** [SnowdogApps/magento2-theme-blank-sass#43]
I've installed this theme and Frontools and everything seems to work. (I'm in developer mode).
Now i would like to use this theme as base for a new one, so i've created `app/design/frontend/MyVendor/MyTheme/theme.xml`:

```
<theme xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Config/etc/theme.xsd">
    <title>MyVendor MyTheme</title> <!-- your theme's name -->
    <parent>Snowdog/blank</parent> <!-- the parent theme, in case your theme inherits from an existing theme -->
    <media>
        <preview_image>preview.jpg</preview_image> <!-- the path to your theme's preview image -->
    </media>
</theme>`
```

and added to frontools themes.json:

```
...
"MyVendor-MyTheme": {
    "src"    : "app/design/frontend/MyVendor/MyTheme",
    "dest"   : "pub/static/frontend/MyVendor/MyTheme",
    "locale" : ["en_US", "it_IT"],
    "lang"   : "scss",
    "postcss": ["plugins.autoprefixer()"]
  }
...
```

Trying to set my new theme in magento backend i get a "broken" site without css.
I cannot figure out how to proceed with the customization. Which is the best practice?

**Comment by Igloczek** [comment]
Theme styles inheritance on tools level isn't ready yet - SnowdogApps/magento2-frontools#22

For now you have to manually copy styles from `blank` to your theme.

**Comment by andyjoneski** [comment]
Please add this to the documentation, as I've been trying to add snow dog as a parent theme for the last hour. Thinking my node had an issue or my gulp was not setup correctly.

**Comment by Igloczek** [comment]
Could you describe your issue or just propose changes in documentation?
Many things changes from May and this issue is not so relevant anymore.

**Comment by andyjoneski** [comment]
Simply needs to mention that snowdog can't be used as a parent theme - which i tried to do with frontools config/themes.json.

**Comment by Igloczek** [comment]
But already you can use this theme as a parent, as you can see in mentioned issue - it's resolved and released in version 0.9.0 of Frontools.

**Comment by andyjoneski** [comment]
This doesn't seem to be the case for myself. Every time i try to use the theme as a parent i get the a gulp throw error. To do with the SRC of the parent theme.

**Comment by Igloczek** [comment]
Could you create a new issue with detailed description, reproduction steps and error messages? I'll try to help you, b/c everything should works fine, almost out of the box.
