### ISSUE TITLE
Different types of labels used in Sass and Blank theme (block vs inline)

### ISSUE THREAD

**Issue by rocketweb-fed** [SnowdogApps/magento2-theme-blank-sass#51]
Forms in Blank (desktop): https://www.evernote.com/shard/s55/sh/3d5eec51-6cd7-46fa-8dfc-178270e36e8a/8da8a91596fb05040fe5de1be02e92d9

Forms in Sass (desktop): https://www.evernote.com/shard/s55/sh/0f9f5dec-2e20-4e98-a548-b9358b502756/73111bd28068cbdbcf3637854b6aff8a

The reason for this difference is missing `lib-form-field-type-revert()` mixin for `fieldset > .field` (for desktops).

Please compare:
Blank: https://github.com/magento/magento2/blob/develop/app/design/frontend/Magento/blank/web/css/source/_forms.less#L167-#L176

Sass: https://github.com/SnowdogApps/magento2-theme-blank-sass/blob/master/web/css/blocks/_forms.scss#L178-#L180

@Igloczek please advise if we should go ahead and include that mixin.

**Comment by Igloczek** [comment]
Go ahead, looks good.

BTW. You rock with this contributions!
