### ISSUE TITLE
lib-css() mixin not being used

### ISSUE THREAD

**Issue by rocketweb-fed** [SnowdogApps/magento2-theme-blank-sass#59]
This mixin is heavily used in the Blank theme for setting css properties within other mixins. It allows to omit properties where falsy variables were specified (i.e. empty strings). 

While making modifications to the Sass theme we've noticed that `inherit` is often used for certain variables which often causes an undesired effect of overwriting selector's rules by its parent. In majority of those cases they should be set to `''` (empty string) which lib-css() mixin allows to do.

By reviewing the commit history I noticed that the lib-css() was initially used in the previous builds but it was removed at some point (with a very intricate message, btw :)). 

@Igloczek, could you please shed some more light on why this mixin is being excluded? Thanks!

**Comment by Igloczek** [comment]
I replaced `''`' with `inherit`, b/c i.e. `block: '';` it's not even close to valid CSS.
Overlapping every use of variable with mixin sucks so hard - it will be about few thousands invokes of same function, which in most cases is useless and leads jest to increase compilation time and unnecessary complexity.
If in some cases variable should be empty just add `if` statement and prevent from printing property.

**Comment by rocketweb-fed** [comment]
Makes sense. Thanks for the explanation. Closing issue.

**Comment by cernfortech** [comment]
Hi @Igloczek , could you please explain why did you back using of lib-css() mixin in this [commit](https://github.com/SnowdogApps/magento2-theme-blank-sass/commit/4eb2c698fe1999268dee2224dd3d9aee56da1bef#diff-90453ed58dc44b74df472733817aebe7)?

**Comment by Igloczek** [comment]
@cernfortech  Since 1.0.0 we changed approach a little bit. This theme now should be an almost ideal representation of  LESS "Blank" theme, so keeping this mixin simplifies maintenance.

**Comment by cernfortech** [comment]
@Igloczek so is your opinion about 

> it will be about few thousands invokes of same function, which in most cases is useless and leads jest to increase compilation time and unnecessary complexity.

the same?

**Comment by Igloczek** [comment]
@cernfortech Yeah, I'm still not a fan of this solution, but since we already created an own theme from scratch, I'm just focused in this project on playing safe 😉

**Comment by cernfortech** [comment]
@Igloczek cool! I’m on my way of developing theme from scratch too so trying understand what useful things I could get from default Magento theme. Is your custom theme is open source project?

**Comment by Igloczek** [comment]
@cernfortech yes it is, but not documented very well yet (it will be useful to show how it works, b/c it's not a typical approach)

Theme: https://github.com/SnowdogApps/magento2-alpaca-theme
Components used to build this theme: https://github.com/SnowdogApps/magento2-alpaca-components
Demo: https://alpaca-ce-demo.snowdog.pro/
Components preview: https://alpaca-components-staging.herokuapp.com/

**Comment by cernfortech** [comment]
@Igloczek thanks! will check it :)
