### ISSUE TITLE
Cannot update to 0.6.0

### ISSUE THREAD

**Issue by slackerzz** [SnowdogApps/magento2-theme-blank-sass#76]
I'm running an ubuntu 16.04 vagrant box and latest php version is 7.0.4
Latest theme release changed composer,json:

```
...
"require": {
    "php": "~5.6.0|7.0.2|~7.0.6",
....
```

so i cannot update

```
- Installation request for snowdog/theme-blank-sass ^0.6.0 -> satisfiable by snowdog/theme-blank-sass[0.6.0].
- snowdog/theme-blank-sass 0.6.0 requires php ~5.6.0|7.0.2|~7.0.6 -> your PHP version (7.0.4) does not satisfy that requirement.
```

Is there any specific problem with php version 7.0.4?

**Comment by Igloczek** [comment]
No idea, I just copy-paste PHP requirements from Magento 2.1 `composer.json` file.
https://github.com/magento/magento2/blob/develop/composer.json

**Comment by slackerzz** [comment]
Ah! Thank you
It seems to be a bug https://github.com/magento/magento2/issues/5131
