### ISSUE TITLE
Magento 2.1 support

### ISSUE THREAD

**Issue by timneutkens** [SnowdogApps/magento2-theme-blank-sass#77]
Hey, we will have to do extensive testing, but it would be good to support the latest version ofcourse.

Diff:
- [x] composer.json
- [x] etc/view.xml
- [x] i18n/en_US.csv
- [x] Magento_AdvancedCheckout/web/css/source/_module.less
- [x] Magento_AdvancedCheckout/web/css/source/_widgets.less
- [x] Magento_Banner/web/css/source/_widgets.less
- [x] Magento_Braintree
- [x] Magento_BraintreeTwo
- [x] Magento_Bundle/web/css/source/_module.less
- [x] Magento_Catalog: layout
- [x] Magento_Catalog/web/css/source/_module.less
- [x] Magento_Catalog/web/css/source/_widgets.less
- [x] Magento_Catalog/web/css/source/module/_listings.less
- [x] Magento_Catalog/web/css/source/module/_toolbar.less
- [x] Magento_CatalogEvent/web/css/source/_module.less
- [x] Magento_CatalogEvent/web/css/source/_widgets.less
- [x] Magento_CatalogSearch/web/css/source/_module.less
- [x] Magento_Checkout: layout
- [x] Magento_Checkout/web/css/source/module/_cart.less
- [x] Magento_Checkout/web/css/source/module/_minicart.less
- [x] Magento_Checkout/web/css/source/module/checkout/_authentication.less
- [x] Magento_Checkout/web/css/source/module/checkout/_checkout.less
- [x] Magento_Checkout/web/css/source/module/checkout/_estimated-total.less
- [x] Magento_Checkout/web/css/source/module/checkout/_fields.less
- [x] Magento_Checkout/web/css/source/module/checkout/_modals.less
- [x] Magento_Checkout/web/css/source/module/checkout/_order-summary.less
- [x] Magento_Checkout/web/css/source/module/checkout/_payment-options.less
- [x] Magento_Checkout/web/css/source/module/checkout/_payments.less
- [x] Magento_Checkout/web/css/source/module/checkout/_progress-bar.less
- [x] Magento_Checkout/web/css/source/module/checkout/_shipping-policy.less
- [x] Magento_Checkout/web/css/source/module/checkout/_shipping.less
- [x] Magento_Checkout/web/css/source/module/checkout/_tooltip.less
- [x] Magento_Cms/web/css/source/_widgets.less
- [x] Magento_Customer: layout
- [x] Magento_Customer/web/css/source/_module.less
- [x] Magento_Downloadable/web/css/source/_module.less
- [x] Magento_GiftCard/web/css/source/_module.less
- [x] Magento_GiftCardAccount: layout
- [x] Magento_GiftCardAccount/web/css/source/_module.less
- [x] Magento_GiftMessage/web/css/source/_module.less
- [x] Magento_GiftRegistry/web/css/source/_module.less
- [x] Magento_GiftWrapping/web/css/source/_module.less
- [x] Magento_GroupedProduct/web/css/source/_module.less
- [x] Magento_Invitation/web/css/source/_module.less
- [x] Magento_LayeredNavigation/web/css/source/_module.less
- [x] Magento_Msrp/web/css/source/_module.less
- [x] Magento_MultipleWishlist/web/css/source/_module.less
- [x] Magento_MultipleWishlist/web/css/source/_widgets.less
- [x] Magento_Multishipping: layout
- [x] Magento_Multishipping/web/css/source/_module.less
- [x] Magento_Newsletter/web/css/source/_module.less
- [x] Magento_Paypal/web/css/source/module/_paypal-button.less
- [x] Magento_Paypal/web/css/source/module/_review.less
- [x] Magento_ProductVideo/web/css/source/_module.less
- [x] Magento_Reports/web/css/source/_widgets.less
- [x] Magento_Review/web/css/source/_module.less
- [x] Magento_Reward/web/css/source/_module.less
- [x] Magento_Rma/web/css/source/_email.less
- [x] Magento_Rma/web/css/source/_module.less
- [x] Magento_Sales/web/css/source/_email.less
- [x] Magento_Sales/web/css/source/_module.less
- [x] Magento_SendFriend/web/css/source/_module.less
- [x] Magento_Theme/layout: default.xml
- [x] Magento_Theme/layout/default_head_blocks.xml
- [x] Magento_Theme/web/css/source: module
- [x] Magento_Theme/web/css/source/_module.less
- [x] Magento_Vault
- [x] Magento_VersionsCms/web/css/source/_widgets.less
- [x] Magento_Weee/web/css/source/_module.less
- [x] Magento_Wishlist/web/css/source/_module.less
- [x] web/css/email-fonts.less
- [x] web/css/print.less
- [x] web/css/source: _dropdowns.less
- [x] web/css/source: _rating.less
- [x] web/css/source/_actions-toolbar.less
- [x] web/css/source/_buttons.less
- [x] web/css/source/_components.less
- [x] web/css/source/_email-base.less
- [x] web/css/source/_email-extend.less
- [x] web/css/source/_extends.less
- [x] web/css/source/_forms.less
- [x] web/css/source/_icons.less
- [x] web/css/source/_layout.less
- [x] web/css/source/_loaders.less
- [x] web/css/source/_navigation.less
- [x] web/css/source/_pages.less
- [x] web/css/source/_popups.less
- [x] web/css/source/_price.less
- [x] web/css/source/_reset.less
- [x] web/css/source/_sources.less
- [x] web/css/source/_tables.less
- [x] web/css/source/_tooltips.less
- [x] web/css/source/_typography.less
- [x] web/css/source/_variables.less
- [x] web/css/source/components/_modals_extend.less
- [x] web/js/responsive.js

**Comment by Igloczek** [comment]
I'll check this next week.

**Comment by timneutkens** [comment]
Cool, thanks!

**Comment by kevincream** [comment]
Does the theme support 2.1 at this moment?

**Comment by Igloczek** [comment]
I have no idea what kind of changes Magento devs made in 2.1 in blank theme.

**Comment by slackerzz** [comment]
@kevincream i've installed version 0.6.0 with Magento 2.1 and i've found some bugs:
- no menu
- no top links
- on product page this requirejs complains about swatchRenderer.js so configurable products are broken and cannot be added to cart

**Comment by Igloczek** [comment]
I made a quick diff 2.0 vs 2.1 and this will require "some" work 😉

**Comment by timneutkens** [comment]
That's quite the list. Think it would be good to create a separate branch for 2.1 support till it's ready, since this will most likely not be backwards compatible.

**Comment by timneutkens** [comment]
@Igloczek you're going fast! Keep up the good work 👍 👍

**Comment by Igloczek** [comment]
Theme support Magento 2.1 up from version 0.7.0.
If you use Magento 2.0 chose version 0.6.0.
