### ISSUE TITLE
Products per row on category pages

### ISSUE THREAD

**Issue by realchriswells** [SnowdogApps/magento2-theme-blank-sass#80]
Everywhere I've looked tells me that I need to change this in the CSS, however everything I've looked at has reference to Luma.

I've looked in the similar place in Snowdog/blank but I couldn't see where to change the number of products per row on category pages. It is set to 4 by default, but I need 3.

Any pointers would be great - thanks.

**Comment by Igloczek** [comment]
Did you try to change variables in `vendor/snowdog/theme-blank-sass/Magento_Catalog/css/source/_module.scss`?

**Comment by realchriswells** [comment]
I did not, I did not realise that existed. I should really pay more attention.

Is there a way to overwrite these in my child theme?

**Comment by Igloczek** [comment]
Most of really useful code is located in modules.
Are you using Frontools?

**Comment by realchriswells** [comment]
I'm not no.

**Comment by Igloczek** [comment]
So I can't provide you any support in customizing this on child theme level, b/c don't know how you work (M2 itself out of the box can't handle theme inheritance and SASS in same time)

Also it's not an issue, just a question - let's move to Magento Community forum - https://community.magento.com/t5/Less-to-Sass-Community-Project/bd-p/less-to-sass
