### ISSUE TITLE
No way to add as parent theme

### ISSUE THREAD

**Issue by andyjoneski** [SnowdogApps/magento2-theme-blank-sass#90]
So i've followed all the steps, step by step (with frontools as well). I've gotten to the point of changing the theme.json and i've added the following: - All of the following exist. 

```
 "modern": {
    "src"    : "app/design/frontend/Attain/modern",
    "dest"   : "pub/static/frontend/Attain/modern",
    "locale" : ["en_GB"],
    "lang"   : "sass",
    "default": "Snowdog/blank",
    "area"   : "frontend",
    "vendor" : "Attain",
    "name"   : "modern"
  },
```

After i do this i run a gulp watch to see if it can see the changes in the files i get the follow error:

```
gulp watch
module.js:327
    throw err;
    ^

Error: Cannot find module './helper/sass'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /Users/andrewjones/Sites/magento2/httpdocs/vendor/snowdog/frontools/gulpfile.js:37:7
    at Array.forEach (native)
    at /Users/andrewjones/Sites/magento2/httpdocs/vendor/snowdog/frontools/gulpfile.js:34:16
    at Array.forEach (native)
    at Object.<anonymous> (/Users/andrewjones/Sites/magento2/httpdocs/vendor/snowdog/frontools/gulpfile.js:32:28)
    at Module._compile (module.js:409:26)
```

**Comment by Igloczek** [comment]
I heavily recommend to read docs and sample configurations precisely, b/c your configuration isn't valid and it's clear that isn't a bug in tools or theme 😉 

Quotes of Frontools docs:

> `lang` - define styles lang want to use for processing, should be same as files extension. Out of the box Frontools supports `less` and `scss`

and

> `parent` - name of parent theme - not available in themes with `default` flag

and

> `default` - (required for default Magento LESS themes) if your theme use default PHP based processing via `bin/magento dev:source-theme:deploy` set this param to true

**Comment by andyjoneski** [comment]
Thanks for the info.
