### ISSUE TITLE
Theme fallback doesn't work

### ISSUE THREAD

**Issue by vphat28** [SnowdogApps/magento2-theme-blank-sass#96]
Hi I extend snowdog/blank in a theme and try to override _typography.scss (actually any file) but it still uses the the file in vendor/snowdog/blank theme . 

Can you please help?

**Comment by Igloczek** [comment]
Did you create styles.scss file in child theme?

**Comment by vphat28** [comment]
hi @Igloczek  yes I copied the styles.scss file

**Comment by Igloczek** [comment]
What version of Frontools are you using? Could you pate here themes.json file content?

**Comment by vphat28** [comment]
frontool is 0.11.4 

i config like this 

"sass-blank": {
    "src"    : "vendor/snowdog/theme-blank-sass",
    "dest"   : "pub/static/frontend/Snowdog/blank",
    "locale" : ["en_AU"],
    "lang"   : "scss",
    "postcss": ["plugins.autoprefixer()"]
  },
  "my-default": {
    "src"    : "app/design/frontend/Xavi/default",
    "dest"   : "pub/static/frontend/Xavi/default",
    "locale" : ["en_US"],
    "parent" :"sass-blank",
    "lang"   : "scss",
    "postcss": ["plugins.autoprefixer()"]
  },

I then make a file in /styles/vendor/magento-ui/variables/_typography.scss in my theme and try to do something but it doesn't apply , maybe I did something wrong

**Comment by Igloczek** [comment]
When you run `gulp styles` did you get something similar to `[12:37:57] Theme: my-default Locale: en_US styles.css Compiled!`?

**Comment by Igloczek** [comment]
This file is loaded via nested imports... and looks like fallback in this case it's broken.
BTW. You shouldn't edit magento-ui files (or any other vendor package). Make any customizations on theme level.

**Comment by vphat28** [comment]
Hi Igloczek yes styles is compiled .

did you mean we should not edit those sass file but should override them in child theme

**Comment by Igloczek** [comment]
If you need more changes than is available through mixin parameters, you should overwrite this mixin on theme level. Vendor code is smth that you shouldn't edit at all.

**Comment by vphat28** [comment]
thank you Igloczek

**Comment by Igloczek** [comment]
I have to investigate inheritance issues at all, so keep I'll keep this open.

**Comment by BenGlassAtlas** [comment]
I seem to be having the same problem, I'm going to investigate later today so I will let you know if I find anything.

**Comment by Igloczek** [comment]
It looks like my inherinace engine might not work well with nested imports, when files have same names, but are placed in many same level directories.

**Comment by BenGlassAtlas** [comment]
@Igloczek Are you aware of any workarounds? All I can think of at the moment is to import a different file (`_custom.scss` for example) in my theme's `styles.scss`.

**Comment by Igloczek** [comment]
Your idea might work, but you can also try to flatten broken imports (import everything on styles.scss level)

**Comment by BenGlassAtlas** [comment]
Hmm ignore me, it's working ok (for me at least).

I had lunch and when I came back it had successfully overwritten sass-blank-theme, I think I needed to cancel `gulp watch` and run it again after the new file was created. I presume watch doesn't automatically pick up new files? I'm using Frontools btw.

**Comment by Igloczek** [comment]
That's right, list of files to watch is generated only on task start.

**Comment by Igloczek** [comment]
Fixed in Frontools v1.0.0
